trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'deploytoaks'
        repository: 'shubhika'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'    

- stage: Deploy
  displayName: Deploy to dev
  dependsOn: Build
  variables:
    acrsecret: deploytoaks
  jobs: 
    - job: Deploy
      displayName: Deploy to AKS
      pool:
        vmImage: ubuntu-latest
      steps: 
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'manifests'
          targetPath: '$(Pipeline.Workspace)/manifests'
      - task: KubectlInstaller@0
        inputs:
          kubectlVersion: 'latest'

      - task: Kubernetes@1
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscriptionEndpoint: 'Azure Pass - Sponsorship()'
          azureResourceGroup: 'aksdemo'
          kubernetesCluster: 'shubhika'
          namespace: 'default'
          command: 'apply'
          useConfigurationFile: true
          configuration: '$(System.DefaultWorkingDirectory)/kubernetes/file.yml'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'Azure Pass - Sponsorship(1)()'
          azureContainerRegistry: 'deploytoaks.azurecr.io'
          forceUpdate: false
              
