apiversion: apps/v1
kind: Deployment
metadata: 
  name: app-deployment
  annotations:
    kubernetes.io/change-cause: "Initial deployment of the app"
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: app
  template: 
    metadata: 
      name: app
      labels:
        env: prod 
        app: app 
        app.kubernetes.io/name: app
    spec:
      containers:
        - name: app 
          image: shubhika25/app:v1
          ports:
            - containerPort: 80
              name: http-web-api
          resources: 
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m 
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80  
---
apiversion: v1
kind: service 
metadata: 
  name: lbservice
spec: 
  selector: 
    app.kubernetes.io/name: app
  ports:
    - name: appport
      protocol: TCP
      port: 8080
      targetport: 80
  type: LoadBalancer

